bite/urls.py
from django.conf.urls import url
from . import views

app_name = 'bite'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^registerorlogin/$', views.RegisterOrLoginView.as_view(), name='registerorlogin'),
    url(r'^signup/$', views.SignupCustomerView.as_view(), name='signup_customer'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^restaurants/signup/$', views.SignupRestaurantView.as_view(), name='signup_restaurant'),
    url(r'^restaurants/$', views.RestaurantListView.as_view(), name='restaurant_list'),
    url(r'^restaurants/add/$', views.RestaurantCreateView.as_view(), name='restaurant_add'),
    url(r'^restaurants/(?P<pk>[0-9]+)/$', views.RestaurantDetailView.as_view(), name='restaurant_detail'),
    url(r'^restaurants/(?P<pk>[0-9]+)/delete/$', views.RestaurantDeleteView.as_view(), name='restaurant_delete'),
    url(r'^restaurants/(?P<pk>[0-9]+)/update/$', views.RestaurantUpdateView.as_view(), name='restaurant_update'),
    url(r'^restaurants/(?P<pk>[0-9]+)/order/$', views.OrderView.as_view(), name='user_order'),
    url(r'^restaurants/(?P<pk>[0-9]+)/order/thanks$', views.IndexView.as_view(), name='user_order_thanks'),
    url(r'^restaurants/(?P<pk>[0-9]+)/our-orders/$', views.OrderListView.as_view(), name='restaurant_orders'),
    url(r'^restaurants/(?P<restaurant_id>[0-9]+)/menu/$', views.DishListView.as_view(), name='dishes_list'),
    url(r'^restaurants/(?P<restaurant_id>[0-9]+)/menu/add/$', views.DishCreateView.as_view(), name='dishes_add'),
    # url(r'^restaurant/(?P<restaurant_id>[0-9]+)/menu/(?P<pk>[0-9]+)/$', views.DishViewView.as_view(), name='dishes_view'),
    url(r'^restaurants/(?P<restaurant_id>[0-9]+)/menu/(?P<pk>[0-9]+)/delete/$', views.DishDeleteView.as_view(), name='dishes_delete'),
    url(r'^restaurants/(?P<restaurant_id>[0-9]+)/menu/(?P<pk>[0-9]+)/update/$', views.DishUpdateView.as_view(), name='dishes_update'),
]

givebite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

SOCIAL_AUTH_URL_NAMESPACE = 'social'
urlpatterns = [
    # url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^', include('bite.urls')),
    url(r'^admin/', admin.site.urls),
]

bite/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=300)
    password = forms.CharField(max_length=300, widget=forms.PasswordInput())


class SignupForm(forms.Form):
    first_name = forms.CharField(max_length=300)
    last_name = forms.CharField(max_length=300)
    username = forms.CharField(max_length=300)
    password = forms.CharField(max_length=300, widget=forms.PasswordInput())
    password_recheck = forms.CharField(max_length=300, widget=forms.PasswordInput())
    email = forms.EmailField(max_length=300)
    # worker_id = forms.IntegerField()

bite/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy, reverse
from django.shortcuts import render, get_object_or_404, get_list_or_404, _get_queryset, redirect
from django.utils.encoding import force_text
from django.views.generic import *
from .models import *

from .forms import *

# Create your views here.
logger = logging.getLogger(__name__)


class RestaurantMixin:
    fields = (
        'name',
        'address',
        'phone',
        'email',
        'active',
        'owner',
        'description',
    )
    success_url = reverse_lazy('bite:restaurant_list')
    model = Restaurant

    # def get(self, request, pk, *args, **kwargs):
    #     """
    #     Overrides get function then adds a model of type Restaurant to the view whose id = restaurant_id
    #     :param restaurant_id: Gets restaurant_id from url (?P<restaurant_id>[0-9]+)
    #     :return: The regular get return. No need to return our self.restaurant model.
    #     """
    #     self.restaurant = get_object_or_404(Restaurant, id=pk)
    #     self.dishes = get_list_or_404(Dish, restaurant=self.restaurant)
    #     return super().get(request, *args, **kwargs)


class IndexView(RestaurantMixin, ListView):
    template_name = 'bite/index.html'
    fields = (
        'name',
        'address',
        'phone',
        'description',
    )
    page_title = "Home"

    # context_object_name = 'latest_question_list'

    # def get_queryset(self):
    #     """Return the last five published questions."""
    #     return None


class RegisterOrLoginView(ListView):
    template_name = 'registerorlogin.html'
    page_title = "Register Or Login"

    # context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return None


class LoginView(FormView):
    page_title = "Login"
    template_name = "login.html"
    form_class = LoginForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect('bite:index')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = authenticate(username=form.cleaned_data['username'],
                            password=form.cleaned_data['password'])

        if user is not None:
            if user.is_active:
                login(self.request, user)
                if self.request.GET.get('from'):
                    return redirect(
                        self.request.GET['from'])  # SECURITY: check path
            else:
                form.add_error(None, "User isn't active anymore - please contact admin")
                return self.form_invalid(form)
        else:
            form.add_error(None, "username doesn't exist")
            return self.form_invalid(form)
        return redirect('bite:index')


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect("bite:index")


class SignupRestaurantView(FormView):
    page_title = "Signup Restaurant User"
    template_name = "login.html"
    form_class = SignupForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect('campaigns:restaurant_list')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        if form.cleaned_data['password'] != form.cleaned_data.pop('password_recheck'):
            form.add_error(None, "Passwords do not match")
            return self.form_invalid(form)
        user = User.objects.create_user(**form.cleaned_data)
        user = authenticate(**form.cleaned_data)

        # Add new user to ProfileUser and CampaignUser Or WriterUser
        restaurant_owner = RestaurantOwner(user=user, )
        restaurant_owner.full_clean()
        restaurant_owner.save()

        # Login
        if user is not None:
            if user.is_active:
                login(self.request, user)
            else:
                form.add_error(None, "Disabled account")
                return self.form_invalid(form)
            if self.request.GET.get('from'):
                return redirect(
                    self.request.GET['from'])  # SECURITY: check path
            return redirect('bite:restaurant_list')


class SignupCustomerView(FormView):
    page_title = "Customer Signup"
    template_name = "login.html"
    form_class = SignupForm
    logger.error("Enter form_valid")

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect('bite:index')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        # logger.error("Enter form_valid")
        if form.cleaned_data['password'] != form.cleaned_data.pop('password_recheck'):
            form.add_error(None, "Passwords do not match")
            return self.form_invalid(form)
        # logger.error("Checked Passwords Match")
        user = User.objects.create_user(**form.cleaned_data)
        user = authenticate(**form.cleaned_data)
        # logger.error("Authenticated User")

        # Add new user to ProfileUser and CampaignUser Or WriterUser
        customer = Customer(user=user, )
        customer.full_clean()
        customer.save()

        # Login
        if user is not None:
            if user.is_active:
                login(self.request, user)
            else:
                form.add_error(None, "Disabled account")
                return self.form_invalid(form)
            if self.request.GET.get('from'):
                return redirect(
                    self.request.GET['from'])  # SECURITY: check path
            return redirect('bite:index')


class RestaurantListView(RestaurantMixin, ListView):
    page_title = "My Restaurants"


class RestaurantDetailView(RestaurantMixin, DetailView):
    page_title = ''

    def get(self, request, pk, *args, **kwargs):
        """
        Overrides get function then adds a model of type Restaurant to the view whose id = restaurant_id
        :param restaurant_id: Gets restaurant_id from url (?P<restaurant_id>[0-9]+)
        :return: The regular get return. No need to return our self.restaurant model.
        """
        self.restaurant = get_object_or_404(Restaurant, id=pk)
        self.page_title = "{} Information".format(self.restaurant.name)

        def get_list_or_none(klass, *args, **kwargs):
            queryset = _get_queryset(klass)
            obj_list = list(queryset.filter(*args, **kwargs))
            if obj_list:
                return obj_list
            return []

        self.dishes = get_list_or_none(Dish, restaurant=self.restaurant)
        self.orders = get_list_or_none(Order, restaurant=self.restaurant)
        return super().get(request, *args, **kwargs)


class RestaurantCreateView(RestaurantMixin, CreateView):
    page_title = "Add Restaurant"


class RestaurantUpdateView(RestaurantMixin, UpdateView):
    page_title = "Update Restaurant"
    button_label = "Update"

    # def get_success_url(self):
    #     if 'restaurant_id' in self.kwargs:
    #         restaurant_id = self.kwargs['restaurant_id']
    #     else:
    #         restaurant_id = 'none'
    #     return reverse('bite:dishes_list', kwargs={'restaurant_id': restaurant_id})


class RestaurantDeleteView(RestaurantMixin, DeleteView):
    page_title = "Delete Restaurant"
    button_label = "Delete"

    # def get_success_url(self):
    #     if 'restaurant_id' in self.kwargs:
    #         restaurant_id = self.kwargs['restaurant_id']
    #     else:
    #         restaurant_id = 'none'
    #     return reverse('bite:dishes_list', kwargs={'restaurant_id': restaurant_id})


class DishListView(ListView):
    page_title = "Restaurant Menu"
    page_name = "Menu"
    model = Dish

    def get(self, request, restaurant_id, *args, **kwargs):
        """
        Overrides get function then adds a model of type Restaurant to the view whose id = restaurant_id
        :param restaurant_id: Gets restaurant_id from url (?P<restaurant_id>[0-9]+)
        :return: The regular get return. No need to return our self.restaurant model.
        """
        self.restaurant = get_object_or_404(Restaurant, id=restaurant_id)
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return super().get_queryset().filter(restaurant=self.restaurant)


class DishMixin:
    fields = (
        'name',
        'price',
        'description',
        # 'restaurant',
        # 'id',
    )
    # success_url = reverse_lazy('bite:dishes_list')
    model = Dish

    def get(self, request, restaurant_id, *args, **kwargs):
        self.restaurant = get_object_or_404(Restaurant, id=restaurant_id)
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        if 'restaurant_id' in self.kwargs:
            restaurant_id = self.kwargs['restaurant_id']
        else:
            restaurant_id = 'none'
        form.instance.restaurant_id = restaurant_id
        return super().form_valid(form)


class DishCreateView(DishMixin, CreateView):
    page_title = "Add Dish"

    def get_success_url(self):
        """
        http://stackoverflow.com/questions/11027996/success-url-in-updateview-based-on-passed-value
        http://stackoverflow.com/questions/30681055/providing-parameters-when-reverse-lazy-ing-a-success-url-redirect
        Changes the success_url in such a way that the restaurant_id is passed as a kwarg for use during creating, updating, deleting.
        :return:
        """
        if 'restaurant_id' in self.kwargs:
            restaurant_id = self.kwargs['restaurant_id']
        else:
            restaurant_id = 'none'
        return reverse('bite:dishes_list', kwargs={'restaurant_id': restaurant_id})


class DishUpdateView(DishMixin, UpdateView):
    page_title = "Update Dish"

bite/templates/base.html
{% load staticfiles %}
{% load bootstrap3 %}
{#https://www.djangorocks.com/snippets/getting-breadcrumbs-in-your-template.html#}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
          crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.5/darkly/bootstrap.min.css" rel="stylesheet"/>
    <!-- Latest compiled and minified JavaScript -->
    {% block css %}
    {% endblock %}
    <style>
        body {
            padding-top: 70px;
        }
              /* Set the fixed height of the footer here */
      #push,
      #footer {
        height: 60px;
      }

      /* Lastly, apply responsive CSS fixes as necessary */
      @media (max-width: 767px) {
        #footer {
          margin-left: -20px;
          margin-right: -20px;
          padding-left: 20px;
          padding-right: 20px;
        }
      }
    </style>
    <title>
        {{ view.page_title }} | GiveBite
    </title>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'bite:index' %}"> GiveBite | So Tasty</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {#                    <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>#}
                {% block mypage %}
                {% endblock %}
                {#                    <li class="dropdown">#}
                {#                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>#}
                {#                      <ul class="dropdown-menu">#}
                {#                        <li><a href="#">Action</a></li>#}
                {#                        <li><a href="#">Another action</a></li>#}
                {#                        <li><a href="#">Something else here</a></li>#}
                {#                        <li role="separator" class="divider"></li>#}
                {#                        <li><a href="#">Separated link</a></li>#}
                {#                        <li role="separator" class="divider"></li>#}
                {#                        <li><a href="#">One more separated link</a></li>#}
                {#                      </ul>#}
                {#                    </li>#}
            </ul>
            {#                  <form class="navbar-form navbar-left" role="search">#}
            {#                    <div class="form-group">#}
            {#                      <input type="text" class="form-control" placeholder="Search">#}
            {#                    </div>#}
            {#                    <button type="submit" class="btn btn-default">Submit</button>#}
            {#                  </form>#}
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
{#                    {{ user.id }}#}
                    <li><a href="#User_Settings">{{ user|title }}</a></li>
                    <li><a href="{% url 'bite:logout' %}">Logout</a></li>
                    <li class="dropdown">
                        {#          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>#}
                        {#          <ul class="dropdown-menu">#}
                        {#            <li><a href="#">Action</a></li>#}
                        {#            <li><a href="#">Another action</a></li>#}
                        {#            <li><a href="#">Something else here</a></li>#}
                        {#            <li role="separator" class="divider"></li>#}
                        {#            <li><a href="#">Separated link</a></li>#}
                        {#          </ul>#}
                    </li>
                {% else %}
                    <li><a href="{% url "bite:registerorlogin" %}">Register or Login</a></li>
                {% endif %}
            </ul>

        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="container-fluid">
    <div>
        {% block breadcrumbs %}
            <ol class="breadcrumb">
            <li><a href="{% url 'bite:index' %}">Home</a></li>
        {% endblock %}
        </ol>
        <hr>
        {% block content %}
        {% endblock %}
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
        crossorigin="anonymous"></script>

{% block scripts %}
{% endblock %}
    <div id="footer">
      <div class="container-fluid">
        <p align="center">Copyright <a href="http://www.alonbukai.com">Alon Bukai</a></p>
      </div>
    </div>
</body>
</html>

bite/templates/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block breadcrumbs %}
    {{ block.super }}
    <li><a href="{{ view.get_absolute_url }}">{{ view.page_title }}</a></li>
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <h1>{{ view.page_title }}</h1>
        <ul>
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">
                {% bootstrap_icon "OK" %} OK
                </button>
            {% endbuttons %}
        </ul>
    </form>
{% endblock %}

bite/templates/registerorlogin.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block breadcrumbs %}
    {{ block.super }}
    <li><a href="{{ view.get_absolute_url }}">{{ view.page_title }}</a></li>
{% endblock %}

{% block content %}
    <h1><a href="{% url "bite:signup_customer" %}">Register</a><br/></h1>
    <h1><a href="{% url "bite:login" %}">Login</a></h1>
{% endblock %}