bite/urls.py
from django.conf.urls import url
from . import views

app_name = 'bite'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^registerorlogin/$', views.RegisterOrLoginView.as_view(), name='registerorlogin'),
    url(r'^signup/$', views.SignupCustomerView.as_view(), name='signup_customer'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^restaurants/signup/$', views.SignupRestaurantView.as_view(), name='signup_restaurant'),
    url(r'^restaurants/$', views.RestaurantListView.as_view(), name='restaurant_list'),
    url(r'^restaurants/add/$', views.RestaurantCreateView.as_view(), name='restaurant_add'),
    url(r'^restaurants/(?P<pk>[0-9]+)/$', views.RestaurantDetailView.as_view(), name='restaurant_detail'),
    url(r'^restaurants/(?P<pk>[0-9]+)/delete/$', views.RestaurantDeleteView.as_view(), name='restaurant_delete'),
    url(r'^restaurants/(?P<pk>[0-9]+)/update/$', views.RestaurantUpdateView.as_view(), name='restaurant_update'),
    url(r'^restaurants/(?P<pk>[0-9]+)/order/$', views.OrderView.as_view(), name='user_order'),
    url(r'^restaurants/(?P<pk>[0-9]+)/order/thanks$', views.IndexView.as_view(), name='user_order_thanks'),
    url(r'^restaurants/(?P<pk>[0-9]+)/our-orders/$', views.OrderListView.as_view(), name='restaurant_orders'),
    url(r'^restaurants/(?P<restaurant_id>[0-9]+)/menu/$', views.DishListView.as_view(), name='dishes_list'),
    url(r'^restaurants/(?P<restaurant_id>[0-9]+)/menu/add/$', views.DishCreateView.as_view(), name='dishes_add'),
    # url(r'^restaurant/(?P<restaurant_id>[0-9]+)/menu/(?P<pk>[0-9]+)/$', views.DishViewView.as_view(), name='dishes_view'),
    url(r'^restaurants/(?P<restaurant_id>[0-9]+)/menu/(?P<pk>[0-9]+)/delete/$', views.DishDeleteView.as_view(), name='dishes_delete'),
    url(r'^restaurants/(?P<restaurant_id>[0-9]+)/menu/(?P<pk>[0-9]+)/update/$', views.DishUpdateView.as_view(), name='dishes_update'),
]

givebite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

SOCIAL_AUTH_URL_NAMESPACE = 'social'
urlpatterns = [
    # url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^', include('bite.urls')),
    url(r'^admin/', admin.site.urls),
]

bite/models.py
import logging
from django.conf import settings
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.core.validators import RegexValidator
from django.db import models
from django.core.validators import MinValueValidator
from django.db.models import Sum
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.
# TODO move this validator to somewhere else!
name_validator = RegexValidator(r'^[a-zA-Z]+$')


class Gender:
    MALE = 1
    FEMALE = 2

    choices = (
        (MALE, 'male'),
        (FEMALE, 'female'),
    )


# TODO add imagaField for restaurant image, resize it.
class Restaurant(models.Model):
    """
    Fields - Name, Address, Phone, Email, Active, Owner, Description
    """
    # Relations
    # Attributes - Mandatory
    name = models.CharField(
        max_length=30,
        # validators=[],
    )
    address = models.CharField(
        max_length=100,
        verbose_name='address',
        help_text='Enter a valid address(City, Street, Number)',
        # TODO regex validator for all languages.
        # validators=[],
    )

    # TODO regex validator for all languages.
    phone = models.CharField(
        max_length=10,
        verbose_name='phone',
        # validators=[],
        help_text='Enter a valid phone number',
    )

    email = models.EmailField(verbose_name='email')

    active = models.BooleanField(default=True)
    owner = models.CharField(max_length=30)
    # Attributes - Optional
    description = models.TextField(blank=True, null=True)
    popularity = models.PositiveIntegerField(default=0, editable=False)

    # Object Manager
    # Custom Properties Methods
    # Meta and String
    class Meta:
        verbose_name = 'restaurant'
        verbose_name_plural = 'restaurants'

    def __str__(self):
        return "{} - {}".format(self.name, self.phone)

    def get_absolute_url(self):
        return reverse('bite:restaurant_detail', args=(self.pk,))


class Dish(models.Model):
    # Relations
    restaurant = models.ForeignKey(
        Restaurant,
        related_name='dishes',
        on_delete=models.CASCADE,
    )
    # Attributes - Mandatory
    name = models.CharField(max_length=50)
    price = models.DecimalField(decimal_places=2, max_digits=7)
    # Attributes - Optional
    description = models.CharField(max_length=100, null=True, blank=True)

    # Object Manager
    # Custom Properties Methods
    # Meta and String

    def __str__(self):
        # if self.restaurant:
        #     return "{}-{}-{}-{}".format(self.name, self.price, self.description, self.restaurant)
        # else:
        return "{}-{}-{}".format(self.name, self.price, self.description)


# class Company(models.Model):
#     # Relations
#     restaurant = models.ManyToManyField(
#         Restaurant,
#         related_name='companies',
#         verbose_name='restaurant',
#         blank=True,
#     )
#     # Attributes - Mandatory
#     name = models.CharField(
#         max_length=30,
#         validators=[],
#     )
#     address = models.CharField(
#         max_length=100,
#         verbose_name='address',
#         help_text='Enter valid address(City, Street, Number)',
#         # TODO regex validator for all languages.
#         validators=[],
#     )
#
#     # TODO regex validator for all languages.
#     phone = models.CharField(
#         max_length=10,
#         verbose_name='phone',
#         validators=[],
#         help_text='Enter valid phone number',
#     )
#
#     email = models.EmailField(verbose_name='email')
#
#     active = models.BooleanField(default=True)
#     owner = models.CharField(max_length=30)
#     # Attributes - Optional
#     description = models.TextField(blank=True, null=True)
#
#     # Object Manager
#     # Custom Properties Methods
#     # Meta and String
#     class Meta:
#         default_related_name = 'companies'
#         verbose_name = 'company'
#         verbose_name_plural = 'companies'

class RestaurantOwner(models.Model):
    # Relations
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='restaurant_owner'
    )

    gender = models.IntegerField(choices=Gender.choices, null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    country = models.CharField(max_length=50, null=True, blank=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)
    state = models.CharField(max_length=50, null=True, blank=True)
    # email = models.EmailField(verbose_name='email')


class Customer(models.Model):
    # Relations
    user = models.OneToOneField(
        User,
        related_name='customers'
    )
    # company = models.ForeignKey(
    #     Company,
    #     on_delete=models.CASCADE,
    #     related_name='customers'
    # )
    # Attributes - Mandatory
    # worker_id = models.IntegerField(primary_key=True)
    # first_name = models.CharField(
    #     max_length=30,
    #     validators=[name_validator],
    # )
    #
    # last_name = models.CharField(
    #     max_length=30,
    #     validators=[name_validator],
    # )

    # email = models.EmailField(verbose_name='email')
    # Attributes - Optional
    # Object Manager
    # Custom Properties Methods
    # Meta and String


class Order(models.Model):
    # Relations
    restaurant = models.ForeignKey(
        Restaurant,
        related_name='order',
        on_delete=models.CASCADE,
    )
    # user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='orders')
    dishes = models.ManyToManyField(
        Dish,
        related_name='orders',
        verbose_name='dish',
        blank=True,
    )

    # def get_total_price(self):
    #     return self.dishes.aggregate(sum=Sum('price'))['sum']

    # Attributes - Mandatory
    # name = models.CharField(max_length=50)
    price = models.DecimalField(decimal_places=2, max_digits=7)

    # Attributes - Optional
    # description = models.CharField(max_length=100, null=True, blank=True)

    # Object Manager
    # Custom Properties Methods
    # Meta and String

    def __str__(self):
        return "ID:#{} - Restaurant: {} - Dishes: {} - Total: ${}".format(self.id, self.restaurant, self.dishes, self.price)

        # def __init__(self, *args, **kwargs):
        #     # self.price = Dish.objects.filter(restaurant=self.restaurant).aggregate(sum=Sum('price'))['sum']
        #     self.price = 5
        #     logger = logging.getLogger(__name__)
        #     logger.error(kwargs)
        #     super().__init__(*args, **kwargs)

bite/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=300)
    password = forms.CharField(max_length=300, widget=forms.PasswordInput())


class SignupForm(forms.Form):
    first_name = forms.CharField(max_length=300)
    last_name = forms.CharField(max_length=300)
    username = forms.CharField(max_length=300)
    password = forms.CharField(max_length=300, widget=forms.PasswordInput())
    password_recheck = forms.CharField(max_length=300, widget=forms.PasswordInput())
    email = forms.EmailField(max_length=300)
    # worker_id = forms.IntegerField()

bite/templates/bite/dish_confirm_delete.html
{% extends "bite/dish_list.html" %}
{% load bootstrap3 %}

{% block breadcrumbs %}
    {{ block.super }}
    <li><a href="{{ view.get_absolute_url }}">{{ view.page_title }}</a></li>
{% endblock %}

{% block mypage %}
    <li><a href="{% url 'bite:restaurant_list' %}">My Restaurants</a></li>
{% endblock %}

{% block content %}
    <p>
        Are you sure you want to delete:<br/>
        Name - {{ object.name }}<br/>
        Price - {{ object.price }}<br/>
        Description - {{ object.description }}<br/>
    </p>
    <form method="post" class="form">
        {% csrf_token %}
        <ul>
            {% buttons %}
                <button type="submit" class="btn btn-danger">
                    {% bootstrap_icon "trash" %} {{ view.button_label|default:'Add' }}
                </button>
            {% endbuttons %}
        </ul>
    </form>
{% endblock %}

bite/templates/bite/dish_form.html
{% extends "bite/dish_list.html" %}
{% load bootstrap3 %}

{% block breadcrumbs %}
    {{ block.super }}
    <li><a href="{{ view.get_absolute_url }}">{{ view.page_title }}</a></li>
{% endblock %}

{% block mypage %}
    <li><a href="{% url 'bite:restaurant_list' %}">My Restaurants</a></li>
{% endblock %}

{% block content %}
    <form method="post" class="form">
        {#    {{ view.message|default:"" }}#}
        {% csrf_token %}
        <ul>
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">
                    {% bootstrap_icon "star" %} {{ view.button_label|default:'Add' }}
                </button>
            {% endbuttons %}
        </ul>
    </form>
{% endblock %}

bite/templates/bite/dish_list.html
{% extends "bite/restaurant_detail.html" %}
{% load staticfiles %}
{% block breadcrumbs %}
    {{ block.super }}
    <li><a href="{% url 'bite:dishes_list' view.restaurant.id %}">Restaurant Menu</a></li>
{% endblock %}

{% block mypage %}
    <li><a href="{% url 'bite:restaurant_list' %}">My Restaurants</a></li>
{% endblock %}

{% block content %}
    <a href="{% url 'bite:dishes_add' view.restaurant.id %}">Add New Dish</a>
    <div class="table-responsive">
        <table id="menuTable" class="table table-hover tablesorter">
            <thead>
            <tr class="info">
                <th>Name</th>
                <th>Price</th>
                <th>Description</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    <td>{{ object.name }}</td>
                    <td>$ {{ object.price }}</td>
                    <td>{{ object.description }}</td>
                    <td><a href="{% url 'bite:dishes_update' view.restaurant.id object.pk %}">Update</a></td>
                    <td><a href="{% url 'bite:dishes_delete' view.restaurant.id object.pk %}">Delete</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block css %}
    <link href="{% static "bite/css/tables.css" %}" rel="stylesheet"/>
{% endblock %}

{% block scripts %}
    <script src="{% static "bite/js/jquery.tablesorter.js" %}"></script>
    <script>
        $(document).ready(function () {
                    $("#menuTable").tablesorter();
                }
        );
    </script>
{% endblock %}

bite/templates/bite/index.html
{% extends "base.html" %}
{% load staticfiles %}

{#{% block mypage %}#}
{#    <li><a href="#register_or_login">Register or Login</a></li>#}
{#{% endblock %}#}

{% block content %}
    {#    {{ view.fields }}#}
    <div class="panel panel-danger">
        <div class="panel-heading text-center">Choose a Restaurant To Order From</div>
{#        <div class="panel-body">Choose a restaurant to order from..</div>#}
    </div>
    <a href="{% url 'bite:restaurant_list' %}">Your Restaurants</a>
    <div class="table-responsive">

        <table id="restTable" class="table table-hover tablesorter">
            <thead>
            <tr class="info">
                {% for field in view.fields %}
                    <th>{{ field|title }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    <td><a href="{% url 'bite:user_order' object.pk %}">{{ object.name }}</a></td>
                    <td>{{ object.address }}</td>
                    <td>{{ object.phone }}</td>
                    <td>{{ object.description }}</td>
                </tr>
            {% endfor %}
            </tbody>
            {#        <tfoot>#}
            {#        <tr>#}
            {#            <td>Total:</td>#}
            {#            <td>$ {{ view.total }}</td>#}
            {#            <td></td>#}
            {#        </tr>#}
            {#        </tfoot>#}
        </table>
    </div>
{% endblock %}

{% block css %}
    <link href="{% static "bite/css/tables.css" %}" rel="stylesheet"/>
{% endblock %}

{% block scripts %}
    <script src="{% static "bite/js/jquery.tablesorter.js" %}"></script>
    <script>
        $(document).ready(function () {
                    $("#restTable").tablesorter();
                }
        );
    </script>
{% endblock %}

bite/templates/bite/order_list.html
{% extends "bite/restaurant_detail.html" %}
{% load staticfiles %}

{% block breadcrumbs %}
    {{ block.super }}
    <li><a href="#OurOrdersPage">Our Orders</a></li>
    {#    <a href="{% url 'bite:dishes_list' view.restaurant.id %}">Restaurant Menu</a>#}
{% endblock %}

{% block mypage %}
    <li><a href="{% url 'bite:restaurant_list' %}">My Restaurants</a></li>
{% endblock %}


{% block content %}
    {#    <a href="{% url 'bite:dishes_add' view.restaurant.id %}">Add Dish</a>#}
    {#        <h3>Click on a dish to add to order</h3>#}
    {% if not object_list %}
        No Orders to display
    {% else %}
        <div class="panel panel-default">
            <div class="panel-heading text-center">Our Orders</div>
            <div class="panel-body">Click on a table header to sort the table.</div>
        </div>
        <div class="table-responsive">
            <table id="myTable" class="table table-hover tablesorter">
                <thead>
                <tr class="info">
                    <th>Order #</th>
                    <th>Date and Time</th>
                    <th>Dishes</th>
                    <th>Total Price</th>
                    <th>Ordered By</th>
                    <th>Phone</th>
                    <th>Address</th>
                    <th>City</th>
                    <th>Completed</th>
                </tr>
                </thead>
                <tbody>
                {% for object in object_list %}
                    <tr>
                        <td>{{ object.id }}</td>
                        <td># TODO Date Time</td>
                        <td>
                            <ul>
                                {% for dish in object.dishes.all %}
                                    <li>
                                        Name: {{ dish.name }}
                                        <ul>
                                            <li>${{ dish.price }}</li>
                                            <li>Description: {{ dish.description }}</li>
                                        </ul>
                                        {#                                    {{ dish }}#}
                                    </li>
                                {% endfor %}
                            </ul>
                        </td>
                        <td>{{ object.price }}</td>
                        <td># TODO Ordered By</td>
                        <td># TODO Phone</td>
                        <td># TODO Address</td>
                        <td># TODO City</td>
                        <td># TODO Completed</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
{% endblock %}

{% block css %}
    <link href="{% static "bite/css/tables.css" %}" rel="stylesheet"/>
{% endblock %}

{% block scripts %}
    <script src="{% static "bite/js/jquery.tablesorter.js" %}"></script>
    <script>
        $(document).ready(function () {
                    $("#myTable").tablesorter();
                }
        );
    </script>
{% endblock %}

bite/templates/bite/order_page.html
{% extends "bite/restaurant_detail.html" %}
{% load staticfiles %}
{% block breadcrumbs %}
    {{ block.super }}
    <li><a href="{% url 'bite:user_order' view.restaurant.id %}">Order</a></li>
    {#    <a href="{% url 'bite:dishes_list' view.restaurant.id %}">Restaurant Menu</a>#}
{% endblock %}

{% block mypage %}
    <li><a href="#User_My_Orders">My Orders</a></li>
{% endblock %}

{% block content %}
    {#    <a href="{% url 'bite:dishes_add' view.restaurant.id %}">Add Dish</a>#}
    <div class="row">
        <div class="col-md-6">
            <h3 align="center">Click on a dish to add to order</h3>
            <div class="table-responsive">
                <table id="menuTable" class="table table-hover tablesorter">
                    <thead>
                    <tr class="info">
                        <th>Name</th>
                        <th>Price</th>
                        <th>Description</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for object in object_list %}
                        <tr data-id="{{ object.id }}">
                            <td>{{ object.name }}</td>
                            <td>$ {{ object.price }}</td>
                            <td>{{ object.description }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {#            <ul id="dishes">#}
            {#                {% for object in object_list %}#}
            {#                    <li data-id="{{ object.id }}" data-price="{{ object.price }}">{{ object.name }} - $ {{ object.price }} - {{ object.restaurant.name }}</li>#}
            {#        <td>{{ object.description }}</td>#}
            {#                {% endfor %}#}
            {#            </ul>#}
        </div>
        <div class="col-md-6">
            <h3 align="center">Click on a dish to remove from order</h3>
            {#            <form action="" method="post">{% csrf_token %}#}
            {#                {{ form.as_p }}#}
            {#                <input type="submit" value="Save"/>#}
            {#            </form>#}
            <div style="border: 1px solid black">
                <form method="post" id="frm">
                    {% csrf_token %}
                    <div class="table-responsive">
                        <table id="orderTable" class="table table-hover tablesorter">
                            <thead>
                            <tr class="info">
                                <th>Name</th>
                                <th>Price</th>
                                <th>Description</th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                    <div style="text-align: center">
                        <p id="price_total">Total: $<span>0</span></p>
                        <button type="button" class="btn btn-default">Order</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block css %}
    <link href="{% static "bite/css/tables.css" %}" rel="stylesheet"/>
{% endblock %}

{% block scripts %}
    <script src="{% static "bite/js/order_page.js" %}"></script>
    <script src="{% static "bite/js/jquery.tablesorter.js" %}"></script>
    <script>
        $(document).ready(function () {
                    $("#menuTable").tablesorter();
                    {#                    $("#orderTable").tablesorter();#}
                }
        );
    </script>
{% endblock %}

bite/templates/bite/restaurant_confirm_delete.html
{% extends "bite/restaurant_list.html" %}
{% load bootstrap3 %}

{% block breadcrumbs %}
    {{ block.super }}
    <li><a href="{{ view.get_absolute_url }}">{{ view.page_title }}</a></li>
{% endblock %}

{% block mypage %}
    <li><a href="{% url 'bite:restaurant_list' %}">My Restaurants</a></li>
{% endblock %}

{% block content %}
    <p>
        Are you sure you want to delete:<br/>
        Name - {{ object.name }}<br/>
        Owner - {{ object.owner }}<br/>
        Description - {{ object.description }}<br/>
    </p>
    <form method="post" class="form">
        {% csrf_token %}
        <ul>
            {% buttons %}
                <button type="submit" class="btn btn-danger">
                    {% bootstrap_icon "trash" %} {{ view.button_label|default:'Add' }}
                </button>
            {% endbuttons %}
        </ul>
    </form>
{% endblock %}

bite/templates/bite/restaurant_detail.html
{% extends "bite/restaurant_list.html" %}
{% load staticfiles %}
{% block breadcrumbs %}
    {{ block.super }}
    {% if not view.restaurant.name %}
        <li><a href="{{ view.restaurant.get_absolute_url }}">{{ object.name }}</a></li>
    {% else %}
        <li><a href="{{ view.restaurant.get_absolute_url }}">{{ view.restaurant.name }}</a></li>
    {% endif %}
{% endblock %}

{% block mypage %}
    <li><a href="{% url 'bite:restaurant_list' %}">My Restaurants</a></li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <h3>Restaurant Menu</h3>
            <p><a href="{% url 'bite:dishes_list' object.id %}">Edit Menu</a></p>
            <div class="table-responsive">
                <table id="menuTable" class="table table-hover tablesorter">
                    <thead>
                    <tr class="info">
                        <th>Name</th>
                        <th>Price</th>
                        <th>Description</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for object in view.dishes %}
                        <tr>
                            <td>{{ object.name }}</td>
                            <td>$ {{ object.price }}</td>
                            <td>{{ object.description }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    {#        <tfoot>#}
                    {#        <tr>#}
                    {#            <td>Total:</td>#}
                    {#            <td>$ {{ view.total }}</td>#}
                    {#            <td></td>#}
                    {#        </tr>#}
                    {#        </tfoot>#}
                </table>
            </div>
        </div>
        <div class="col-md-6">
            <h3 class="text-center">Orders</h3>
            <p><a href="{% url 'bite:restaurant_orders' object.id %}">View Orders</a></p>
            {% if not view.orders %}
                No Orders to display
            {% else %}
                <div class="table-responsive">
                    <table id="orderTable" class="table table-hover tablesorter">
                        <thead>
                        <tr class="info">
                            <th>Order #</th>
                            <th>Date and Time</th>
                            <th>Total Price</th>
                            <th>Ordered By</th>
                            <th>Completed</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for object in view.orders %}
                            <tr>
                                <td>{{ object.id }}</td>
                                <td># TODO Date Time</td>
                                <td>{{ object.price }}</td>
                                <td># TODO Ordered By</td>
                                <td># TODO Completed</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block css %}
    <link href="{% static "bite/css/tables.css" %}" rel="stylesheet"/>
{% endblock %}

{% block scripts %}
    <script src="{% static "bite/js/jquery.tablesorter.js" %}"></script>
    <script>
        $(document).ready(function () {
                    $("#menuTable").tablesorter();
                    $("#orderTable").tablesorter();
                }
        );
    </script>
{% endblock %}

bite/templates/bite/restaurant_form.html
{% extends "bite/restaurant_list.html" %}
{% load bootstrap3 %}

{% block breadcrumbs %}
    {{ block.super }}
        <li><a href="{{ view.get_absolute_url }}">{{ view.page_title }}</a></li>
{% endblock %}

{% block mypage %}
    <li><a href="{% url 'bite:restaurant_list' %}">My Restaurants</a></li>
{% endblock %}

{% block content %}
    <form method="post" class="form">
        {#    {{ view.message|default:"" }}#}
        {% csrf_token %}
        <ul>
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">
                    {% bootstrap_icon "star" %} {{ view.button_label|default:'Add' }}
                </button>
            {% endbuttons %}
        </ul>
    </form>
{% endblock %}

bite/templates/bite/restaurant_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block breadcrumbs %}
    {{ block.super }}
    <li><a href="{% url 'bite:restaurant_list' %}">Restaurants</a></li>
{% endblock %}

{% block mypage %}
    <li><a href="{% url 'bite:restaurant_list' %}">My Restaurants</a></li>
{% endblock %}

{% block content %}
    {#    {{ view.fields }}#}
    <a href="{% url 'bite:restaurant_add' %}">Add Restaurant</a>
    <div class="table-responsive">
        <table id="restTable" class="table table-hover tablesorter">
            <thead>
            <tr class="info">
                {% for field in view.fields %}
                    <th>{{ field|title }}</th>
                {% endfor %}
                <th>Update</th>
                <th>Delete</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    <td><a href="{% url 'bite:restaurant_detail' object.pk %}">{{ object.name }}</a></td>
                    <td>{{ object.address }}</td>
                    <td>{{ object.phone }}</td>
                    <td>{{ object.email }}</td>
                    <td>{{ object.active }}</td>
                    <td>{{ object.owner }}</td>
                    <td>{{ object.description }}</td>
                    <td><a href="{% url 'bite:restaurant_update' object.pk %}">Update</a></td>
                    <td><a href="{% url 'bite:restaurant_delete' object.pk %}">Delete</a></td>
                </tr>
            {% endfor %}
            </tbody>
            {#        <tfoot>#}
            {#        <tr>#}
            {#            <td>Total:</td>#}
            {#            <td>$ {{ view.total }}</td>#}
            {#            <td></td>#}
            {#        </tr>#}
            {#        </tfoot>#}
        </table>
    </div>
{% endblock %}

{% block css %}
    <link href="{% static "bite/css/tables.css" %}" rel="stylesheet"/>
{% endblock %}

{% block scripts %}
    <script src="{% static "bite/js/jquery.tablesorter.js" %}"></script>
    <script>
        $(document).ready(function () {
                    $("#restTable").tablesorter();
                }
        );
    </script>
{% endblock %}